USE [master]
GO
/****** Object:  Database [WorkDemo]    Script Date: 18/10/2022 18:34:24 ******/
CREATE DATABASE [WorkDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WorkDemo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WorkDemo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WorkDemo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WorkDemo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [WorkDemo] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WorkDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [WorkDemo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [WorkDemo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [WorkDemo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [WorkDemo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [WorkDemo] SET ARITHABORT OFF 
GO
ALTER DATABASE [WorkDemo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [WorkDemo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [WorkDemo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [WorkDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [WorkDemo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [WorkDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [WorkDemo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [WorkDemo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [WorkDemo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [WorkDemo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [WorkDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [WorkDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [WorkDemo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [WorkDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [WorkDemo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [WorkDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [WorkDemo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [WorkDemo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [WorkDemo] SET  MULTI_USER 
GO
ALTER DATABASE [WorkDemo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [WorkDemo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [WorkDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [WorkDemo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [WorkDemo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [WorkDemo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [WorkDemo] SET QUERY_STORE = OFF
GO
USE [WorkDemo]
GO
/****** Object:  Table [dbo].[Movies]    Script Date: 18/10/2022 18:34:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movies](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](100) NOT NULL,
	[Release] [date] NULL,
	[Runtime] [varchar](50) NULL,
	[Director] [varchar](50) NULL,
	[Actors] [varchar](100) NULL,
	[Genre] [varchar](50) NULL,
	[Rating] [float] NULL,
 CONSTRAINT [PK_Movies] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[Movies_GetByTitle]    Script Date: 18/10/2022 18:34:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[Movies_GetByTitle] @Title varchar(100)
AS
SELECT * FROM Movies
WHERE Title=@Title
GO
/****** Object:  StoredProcedure [dbo].[Movies_GetByYear]    Script Date: 18/10/2022 18:34:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[Movies_GetByYear] @Year date
AS
SELECT * FROM Movies
WHERE YEAR(Release)=YEAR(@Year)
GO
/****** Object:  StoredProcedure [dbo].[Movies_Insert]    Script Date: 18/10/2022 18:34:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[Movies_Insert] @Title varchar(100), @Release date, @Runtime varchar(50), @Director varchar(50), @Actors varchar(100), @Genre varchar(50), @Rating float
AS
INSERT INTO Movies (Title, Release, Runtime, Director, Actors, Genre, Rating)
VALUES (@Title, @Release, @Runtime, @Director, @Actors, @Genre, @Rating)
GO
USE [master]
GO
ALTER DATABASE [WorkDemo] SET  READ_WRITE 
GO
